import Head from 'next/head'
import Nav from '../components/Nav/Nav'
import Header from '../components/Header/Header'
import Search from '../components/Search'
import PanelItem from '../components/PanelItem'
import Panel from '../components/Panel'
import PanelItemTrends from '../components/PanelItemTrends'
import Footer from '../components/Footer'
import Tabs from '../components/Tabs/Tabs'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen flex max-w-7xl mx-auto xl:grid xl:grid-cols-10 gap-5">
        <Nav />
        <main className="col-span-5 w-full border-x border-slate-200">
          <Header title="Home" href="/" />
          <Tabs />
        </main>
        <aside className="col-span-3 hidden xl:flex flex-col w-[350px]">
          <div className="sticky top-0">
            <Search />
            <Panel title="What's happening" href="/">   
              <PanelItemTrends title="Next JS" category="Development" stat="57.5K" />
              <PanelItemTrends title="Figma" category="Design" stat="107.5K" />
              <PanelItemTrends title="Webflow" category="Design" stat="127.5K" />
              <PanelItemTrends title="Tailwind CSS" category="Development" stat="87.5K" />
              <PanelItemTrends title="Vercel" category="Development" stat="27.5K" />
            </Panel>
            <Panel title="Who to follow" href="/">   
              <PanelItem name="Roy Quilor" username="royquilor" />
              <PanelItem name="Roy Quilor" username="royquilor" />
              <PanelItem name="Roy Quilor" username="royquilor" />
            </Panel>
            <Footer />
          </div>
        </aside>
      </div>
    </>
  )
}
