import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Post from '../components/Post'
import PostForm from '../components/PostForm'
import Bio from '../components/Bio'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
      <div className="max-w-2xl mx-auto p-8">
          <Bio
avatar = "https://pbs.twimg.com/profile_images/1489998205236527108/q2REh8nW_400x400.jpg"
name = "Roy Quilor"
tagline = "Helping beginners learn design"
role = "Designer @ awwesome"
/>
          <PostForm />
          <ul className="[&_p:last-child]:text-slate-500 [&_p:first-child]:text-lg divide-y divide-slate-200">
            <li className="py-10">
              <Post content="Let's create design and build templates" date="3/1/2023" />
            </li>
            <li className="py-10">
              <Post content="I love Figma" date="2/1/2023" />
            </li>
            <li className="py-10">
              <Post content="Tailwind CSS is insane" date="1/1/2023" />
            </li>
            
        </ul>

        </div>
      
    </>
  )
}
